
#
[[operation]]
id = 0
init = true
run-all = true # rerun when using run-all to ensure config is valid
depends-on = []
script_type = "lua"
script = "{{Game_Root}}/operations/init.lua"


#
[[operation]]
id = 3
Name = "Download Required Tools"
run-all = true
depends-on = [0]
script_type = "engine"
script = "download-tools"
tools_manifest = "{{Game_Root}}/Tools.toml"


# ffmpeg -i .\credits.rmv -c:v libx264 -preset fast -crf 23 -c:a aac output.mp4
# ffmpeg -i .\credits.rmv -map 0:v -map 0:a:0 -c:v libtheora -q:v 7 -c:a libvorbis -q:a 4 output.ogv
[[operation]]
id = 4
Name = "Convert Videos (.rmv -> .ogv)"
run-all = true
depends-on = [3] # depends on ffmpeg being downloaded
script_type = "engine"
script = "format-convert"
tool = "ffmpeg"
args = [
    "-m", "ffmpeg",
    "--type", "video",
    "-s", "{{SourcePath}}/movies",
    "-t", "{{Game_Root}}/GameFiles/movies",
    "-i", ".rmv",
    "-o", ".ogv",
    "--video-codec", "libtheora",
    "--video-quality", "7",
    "--audio-codec", "libvorbis",
    "--audio-quality", "4",
    "--replace" # deletes the original .rmv files after conversion
]


## convert Audio into a usable format for godot
[[operation]]
id = 5
Name = "Convert Audio (.rsd -> .wav)"
run-all = true
depends-on = [3] # depends on vgmstream being downloaded
script_type = "engine"
script = "format-convert"
tool = "vgmstream"
args = [
    "-m", "vgmstream",
    "--type", "audio",
    "-s", "{{SourcePath}}/sound",
    "-t", "{{Game_Root}}/GameFiles/sound",
    "-i", ".rsd",
    "-o", ".wav",
    "--godot-compatible",
    "--replace"
]


[[operation]]
id = 6
Name = "convert 'sound/typ/srrtypes.typ' file to .json"
run-all = true
depends-on = []
script_type = "lua"
script = "{{Game_Root}}/operations/format/typ.lua"
args = [
    "{{SourcePath}}/sound/typ/srrtypes.typ",
    "{{Game_Root}}/GameFiles/sound/typ/srrtypes.json"
]



[[operation]]
id = 7
Name = "Extract Archives (.rcf)"
run-all = true
depends-on = [3] # depends on qbms tool
script_type = "bms"
script = "{{Game_Root}}/operations/Scripts/atg_core_cement.bms"
input = "{{SourcePath}}/"
output = "{{Game_Root}}/GameFiles/"
extension = ".rcf"

## convert Audio into a usable format for godot
[[operation]]
id = 8
Name = "Convert extracted Audio (.rsd -> .wav)"
run-all = true
depends-on = [7,3] # depends on vgmstream being downloaded
script_type = "engine"
script = "format-convert"
tool = "vgmstream"
args = [
    "-m", "vgmstream",
    "--type", "audio",
    "-s", "{{Game_Root}}/GameFiles/",
    "-t", "{{Game_Root}}/GameFiles/",
    "-i", ".rsd",
    "-o", ".wav",
    "--godot-compatible",
    "--replace"
]


[[operation]]
id = 9
Name = "Copy Source Files"
run-all = true
depends-on = [1]
script_type = "lua"
script = "{{Game_Root}}/operations/CopySourceFiles.lua"
args = [
    "--source", "{{SourcePath}}",
    "--target", "{{Game_Root}}/GameFiles/",
    "--move"
]
